Repository GreenBlitz/CRRRRESCENDO, pull requests merged in 2024-02, with the labels that each got.

#104 Neo Roller
  src/main/java/edu/greenblitz/robotName/OI.java
  src/main/java/edu/greenblitz/robotName/RobotConstants.java
  src/main/java/edu/greenblitz/robotName/commands/arm/ScoreToAmp.java
  src/main/java/edu/greenblitz/robotName/commands/arm/roller/ReleaseNote.java
  src/main/java/edu/greenblitz/robotName/commands/arm/roller/RollClockWise.java
  src/main/java/edu/greenblitz/robotName/commands/arm/roller/RollClockwise.java
  src/main/java/edu/greenblitz/robotName/commands/arm/roller/RollClockwiseForAGivenTime.java
  src/main/java/edu/greenblitz/robotName/commands/arm/roller/RollCounterClockWise.java
  src/main/java/edu/greenblitz/robotName/commands/arm/roller/RollCounterClockwise.java
  src/main/java/edu/greenblitz/robotName/commands/arm/roller/RollerCommand.java
  src/main/java/edu/greenblitz/robotName/commands/arm/roller/RunRollerClockwiseUntilObjectIsOut.java
  src/main/java/edu/greenblitz/robotName/commands/arm/roller/RunRollerCounterClockwiseUntilNoteIsInside.java
  src/main/java/edu/greenblitz/robotName/commands/getNoteToSystem/MoveNoteBetweenShooterAndArm.java
  src/main/java/edu/greenblitz/robotName/subsystems/Intake/neoIntake/NeoIntake.java
  src/main/java/edu/greenblitz/robotName/subsystems/Intake/neoIntake/NeoIntakeConstants.java
  src/main/java/edu/greenblitz/robotName/subsystems/arm/roller/NeoRoller/NeoRoller.java
  src/main/java/edu/greenblitz/robotName/subsystems/arm/roller/NeoRoller/NeoRollerConstants.java
  src/main/java/edu/greenblitz/robotName/subsystems/arm/roller/Roller.java
  src/main/java/edu/greenblitz/robotName/subsystems/arm/roller/RollerConstants.java
  src/main/java/edu/greenblitz/robotName/subsystems/arm/roller/RollerFactory.java
  src/main/java/edu/greenblitz/robotName/utils/motors/GBSparkMax.java
Labels: feature-improvement

#97 Shooting commands and calculations
  .gitignore
  src/main/java/edu/greenblitz/robotName/Field.java
  src/main/java/edu/greenblitz/robotName/FieldConstants.java
  src/main/java/edu/greenblitz/robotName/OI.java
  src/main/java/edu/greenblitz/robotName/Robot.java
  src/main/java/edu/greenblitz/robotName/commands/auto/MoveToPosition.java
  src/main/java/edu/greenblitz/robotName/commands/shooter/MoveShooterToAngle.java
  src/main/java/edu/greenblitz/robotName/commands/shooter/PushNoteToFlyWheel.java
  src/main/java/edu/greenblitz/robotName/commands/shooter/flyWheel/FlyWheelCommand.java
  src/main/java/edu/greenblitz/robotName/commands/shooter/flyWheel/RunFlyWheelByApropriateVelocity.java
  src/main/java/edu/greenblitz/robotName/commands/shooter/flyWheel/RunFlyWheelByPower.java
  src/main/java/edu/greenblitz/robotName/commands/shooter/flyWheel/RunFlyWheelByPowerConstant.java
  src/main/java/edu/greenblitz/robotName/commands/shooter/flyWheel/RunFlyWheelByVelocity.java
  src/main/java/edu/greenblitz/robotName/commands/shooter/flyWheel/StopFlyWheel.java
  src/main/java/edu/greenblitz/robotName/commands/shooter/funnel/FunnelCommand.java
  src/main/java/edu/greenblitz/robotName/commands/shooter/funnel/RunFunnelByRotations.java
  src/main/java/edu/greenblitz/robotName/commands/shooter/funnel/runByPowerUntilCondition/ForwardRunFunnelUntilObjectIn.java
  src/main/java/edu/greenblitz/robotName/commands/shooter/funnel/runByPowerUntilCondition/ForwardRunFunnelUntilObjectOut.java
  src/main/java/edu/greenblitz/robotName/commands/shooter/funnel/runByPowerUntilCondition/ReverseRunFunnelUntilObjectOut.java
  src/main/java/edu/greenblitz/robotName/commands/shooter/funnel/runByPowerUntilCondition/RunFunnelByPower.java
  src/main/java/edu/greenblitz/robotName/commands/shooter/funnel/runByPowerUntilCondition/RunFunnelByPowerUntilCondition.java
  src/main/java/edu/greenblitz/robotName/commands/shooter/pivot/MovePivotIfInDangerZone.java
  src/main/java/edu/greenblitz/robotName/commands/shooter/pivot/MovePivotToAngle.java
  src/main/java/edu/greenblitz/robotName/commands/shooter/shootingState/GoToShootingState.java
  src/main/java/edu/greenblitz/robotName/commands/shooter/shootingState/GoToShootingStateAndShoot.java
  src/main/java/edu/greenblitz/robotName/commands/shooter/shootingState/MoveRobotToShootingPosition.java
  src/main/java/edu/greenblitz/robotName/commands/swerve/MoveByJoysticks.java
  src/main/java/edu/greenblitz/robotName/commands/swerve/MoveToAmp.java
  src/main/java/edu/greenblitz/robotName/commands/swerve/MoveToClimbPosition.java
  src/main/java/edu/greenblitz/robotName/commands/swerve/MoveToPosition.java
  src/main/java/edu/greenblitz/robotName/commands/swerve/MoveToSpeaker.java
  src/main/java/edu/greenblitz/robotName/commands/swerve/RotateToAngle.java
  src/main/java/edu/greenblitz/robotName/shootingStateService/ShootingPositionConstants.java
  src/main/java/edu/greenblitz/robotName/shootingStateService/ShootingStateCalculations.java
  src/main/java/edu/greenblitz/robotName/subsystems/Gyros/SimulationGyro.java
  src/main/java/edu/greenblitz/robotName/subsystems/shooter/FlyWheel/FalconFlyWheel/FalconFlyWheel.java
  src/main/java/edu/greenblitz/robotName/subsystems/shooter/FlyWheel/FlyWheel.java
  src/main/java/edu/greenblitz/robotName/subsystems/shooter/FlyWheel/FlyWheelConstants.java
  src/main/java/edu/greenblitz/robotName/subsystems/shooter/FlyWheel/NeoFlyWheel/NeoFlyWheelConstants.java
  src/main/java/edu/greenblitz/robotName/subsystems/shooter/FlyWheel/simulationFlyWheel/SimulationFlyWheelConstants.java
  src/main/java/edu/greenblitz/robotName/subsystems/shooter/Funnel/Funnel.java
  src/main/java/edu/greenblitz/robotName/subsystems/shooter/Funnel/FunnelConstants.java
  src/main/java/edu/greenblitz/robotName/subsystems/shooter/Funnel/FunnelInputs.java
  src/main/java/edu/greenblitz/robotName/subsystems/shooter/Funnel/IFunnel.java
  src/main/java/edu/greenblitz/robotName/subsystems/shooter/Funnel/NeoFunnel/NeoFunnel.java
  src/main/java/edu/greenblitz/robotName/subsystems/shooter/Funnel/NeoFunnel/NeoFunnelConstants.java
  src/main/java/edu/greenblitz/robotName/subsystems/shooter/Funnel/ReplayFunnel.java
  src/main/java/edu/greenblitz/robotName/subsystems/shooter/Funnel/SimulationFunnel/SimulationFunnel.java
  src/main/java/edu/greenblitz/robotName/subsystems/shooter/Funnel/SimulationFunnel/SimulationFunnelConstants.java
  src/main/java/edu/greenblitz/robotName/subsystems/shooter/Pivot/PivotConstants.java
  src/main/java/edu/greenblitz/robotName/subsystems/shooter/Pivot/SimulationPivot/SimulationPivot.java
  src/main/java/edu/greenblitz/robotName/subsystems/swerve/Chassis/ChassisConstants.java
  src/main/java/edu/greenblitz/robotName/subsystems/swerve/Chassis/SwerveChassis.java
  src/main/java/edu/greenblitz/robotName/utils/FMSUtils.java
  src/main/java/edu/greenblitz/robotName/utils/GBCircle.java
  src/main/java/edu/greenblitz/robotName/utils/GBMath.java
  src/main/java/edu/greenblitz/robotName/utils/shootingCalculations/Bound.java
  src/main/java/edu/greenblitz/robotName/utils/shootingCalculations/ShootingAngleCalculations.java
  src/main/java/edu/greenblitz/robotName/utils/shootingCalculations/ShootingZone.java
Labels: new-feature, high-priority

#101 yoav - Rollers joystick commands (waiting for the funnel) (doi not merge)
  src/main/java/edu/greenblitz/robotName/OI.java
  src/main/java/edu/greenblitz/robotName/RobotConstants.java
  src/main/java/edu/greenblitz/robotName/commands/arm/roller/RunRollerByJoystick.java
  src/main/java/edu/greenblitz/robotName/commands/intake/RunIntakeByJoystick.java
  src/main/java/edu/greenblitz/robotName/commands/shooter/flyWheel/RunFlyWheelByJoystick.java
  src/main/java/edu/greenblitz/robotName/commands/shooter/funnel/RunFunnelByJoystick.java
  src/main/java/edu/greenblitz/robotName/subsystems/Intake/neoIntake/NeoIntakeConstants.java
  src/main/java/edu/greenblitz/robotName/subsystems/arm/roller/NeoRoller/NeoRollerConstants.java
Labels: new-feature

#105 hillel - run flywheel by velocity working constants
  src/main/java/edu/greenblitz/robotName/subsystems/shooter/FlyWheel/FlyWheelConstants.java
  src/main/java/edu/greenblitz/robotName/subsystems/shooter/FlyWheel/simulationFlyWheel/SimulationFlyWheelConstants.java
Labels: bug-fix

#106 yoav - Fix pivot
  src/main/java/edu/greenblitz/robotName/RobotConstants.java
  src/main/java/edu/greenblitz/robotName/subsystems/shooter/Pivot/FalconPivot/FalconPivot.java
  src/main/java/edu/greenblitz/robotName/subsystems/shooter/Pivot/FalconPivot/FalconPivotConstants.java
  src/main/java/edu/greenblitz/robotName/subsystems/shooter/Pivot/IPivot.java
  src/main/java/edu/greenblitz/robotName/subsystems/shooter/Pivot/Pivot.java
  src/main/java/edu/greenblitz/robotName/subsystems/shooter/Pivot/PivotConstants.java
  src/main/java/edu/greenblitz/robotName/subsystems/shooter/Pivot/PivotInputs.java
  src/main/java/edu/greenblitz/robotName/subsystems/shooter/Pivot/ReplayPivot.java
  src/main/java/edu/greenblitz/robotName/subsystems/shooter/Pivot/SimulationPivot/SimulationPivot.java
  src/main/java/edu/greenblitz/robotName/subsystems/shooter/Pivot/SimulationPivot/SimulationPivotConstants.java
Labels: bug-fix, feature-improvement

#103 robot type chooser -> master
  src/main/java/edu/greenblitz/robotName/Robot.java
  src/main/java/edu/greenblitz/robotName/subsystems/Gyros/GyroFactory.java
  src/main/java/edu/greenblitz/robotName/subsystems/Intake/IntakeFactory.java
  src/main/java/edu/greenblitz/robotName/subsystems/Intake/neoIntake/NeoIntakeConstants.java
  src/main/java/edu/greenblitz/robotName/subsystems/Lifter/LifterFactory.java
  src/main/java/edu/greenblitz/robotName/subsystems/arm/elbow/ElbowFactory.java
  src/main/java/edu/greenblitz/robotName/subsystems/arm/roller/RollerFactory.java
  src/main/java/edu/greenblitz/robotName/subsystems/arm/wrist/WristFactory.java
  src/main/java/edu/greenblitz/robotName/subsystems/shooter/FlyWheel/FlyWheelFactory.java
  src/main/java/edu/greenblitz/robotName/subsystems/shooter/Funnel/FunnelFactory.java
  src/main/java/edu/greenblitz/robotName/subsystems/shooter/Pivot/PivotFactory.java
  src/main/java/edu/greenblitz/robotName/subsystems/swerve/Chassis/SwerveChassis.java
  src/main/java/edu/greenblitz/robotName/subsystems/swerve/Modules/SwerveModuleFactory.java
Labels: bug-fix, new-feature

#107 yoav - fix shooting length and shooter wiggly wiggly in sim
  src/main/java/edu/greenblitz/robotName/OI.java
  src/main/java/edu/greenblitz/robotName/RobotConstants.java
  src/main/java/edu/greenblitz/robotName/shootingStateService/ShootingPositionConstants.java
  src/main/java/edu/greenblitz/robotName/shootingStateService/ShootingStateCalculations.java
  src/main/java/edu/greenblitz/robotName/subsystems/shooter/Pivot/PivotConstants.java
  src/main/java/edu/greenblitz/robotName/subsystems/shooter/Pivot/SimulationPivot/SimulationPivotConstants.java
Labels: bug-fix, feature-improvement

#109 Deprecate deprecated!!!
  src/main/java/edu/greenblitz/robotName/subsystems/Intake/IntakeConstants.java
  src/main/java/edu/greenblitz/robotName/subsystems/Intake/neoIntake/NeoIntake.java
  src/main/java/edu/greenblitz/robotName/subsystems/Intake/neoIntake/NeoIntakeConstants.java
  src/main/java/edu/greenblitz/robotName/subsystems/Lifter/NeoLifter/NeoLifterConstants.java
  src/main/java/edu/greenblitz/robotName/subsystems/arm/elbow/NeoElbow/NeoElbow.java
  src/main/java/edu/greenblitz/robotName/subsystems/arm/roller/BagRoller/BagRoller.java
  src/main/java/edu/greenblitz/robotName/subsystems/arm/wrist/NeoWrist/NeoWrist.java
  src/main/java/edu/greenblitz/robotName/subsystems/swerve/Chassis/SwerveChassis.java
Labels: bug-fix

#110 Flywheel velocity constant
  src/main/java/edu/greenblitz/robotName/commands/shooter/PushNoteToFlyWheel.java
  src/main/java/edu/greenblitz/robotName/commands/shooter/flyWheel/FlyWheelCommand.java
  src/main/java/edu/greenblitz/robotName/commands/shooter/flyWheel/RunFlyWheelByJoystick.java
  src/main/java/edu/greenblitz/robotName/commands/shooter/flyWheel/RunFlyWheelBySpeakerInterpolationVelocity.java
  src/main/java/edu/greenblitz/robotName/commands/shooter/flyWheel/RunFlyWheelByVelocity.java
  src/main/java/edu/greenblitz/robotName/commands/shooter/flyWheel/RunFlyWheelByVelocityConstant.java
  src/main/java/edu/greenblitz/robotName/commands/shooter/flyWheel/StopFlyWheel.java
  src/main/java/edu/greenblitz/robotName/commands/shooter/shootingState/GoToShootingState.java
  src/main/java/edu/greenblitz/robotName/subsystems/shooter/FlyWheel/FlyWheelConstants.java
Labels: bug-fix, feature-improvement

#85 **Don't merge until tested** - Adding the autonomim
  src/main/deploy/pathplanner/autos/1 to 2 to 3.auto
  src/main/deploy/pathplanner/autos/3 to 6 to 5.auto
  src/main/deploy/pathplanner/autos/5 to 1 to 6.auto
  src/main/deploy/pathplanner/autos/7 to 8 to 3.auto
  src/main/deploy/pathplanner/paths/1 to 2.path
  src/main/deploy/pathplanner/paths/1 to 6.path
  src/main/deploy/pathplanner/paths/2 to 3.path
  src/main/deploy/pathplanner/paths/3 to 6.path
  src/main/deploy/pathplanner/paths/5 to 1.path
  src/main/deploy/pathplanner/paths/5 to shoot.path
  src/main/deploy/pathplanner/paths/6 shoot to 5.path
  src/main/deploy/pathplanner/paths/6 to shoot.path
  src/main/deploy/pathplanner/paths/7 shoot to 8.path
  src/main/deploy/pathplanner/paths/7 to shoot.path
  src/main/deploy/pathplanner/paths/8 to 3.path
  src/main/deploy/pathplanner/paths/amp start to 1.path
  src/main/deploy/pathplanner/paths/amp start to 5.path
  src/main/deploy/pathplanner/paths/source start to 7.path
  src/main/deploy/pathplanner/paths/speaker start to 3.path
  src/main/java/edu/greenblitz/robotName/Robot.java
Labels: waiting-for-another-pr, in-testing

#114 Fixed Simulation orientation
  src/main/java/edu/greenblitz/robotName/subsystems/Lifter/Lifter.java
  src/main/java/edu/greenblitz/robotName/subsystems/Lifter/LifterConstants.java
  src/main/java/edu/greenblitz/robotName/subsystems/arm/elbow/Elbow.java
  src/main/java/edu/greenblitz/robotName/subsystems/arm/elbow/ElbowConstants.java
  src/main/java/edu/greenblitz/robotName/subsystems/arm/wrist/Wrist.java
  src/main/java/edu/greenblitz/robotName/subsystems/shooter/Pivot/Pivot.java
  src/main/java/edu/greenblitz/robotName/subsystems/shooter/Pivot/PivotConstants.java
Labels: Bug-Fix

#115 Autonomous chooser 2 electric boogaloo
  src/main/java/edu/greenblitz/robotName/Robot.java
  src/main/java/edu/greenblitz/robotName/subsystems/swerve/Chassis/ChassisConstants.java
  src/main/java/edu/greenblitz/robotName/subsystems/swerve/Chassis/SwerveChassis.java
  src/main/java/edu/greenblitz/robotName/utils/AutonomousSelector.java
Labels: New Feature

#116 Ran-Default shooting and Shooting from close range
  src/main/java/edu/greenblitz/robotName/commands/shooter/ShootFromCloseRange.java
  src/main/java/edu/greenblitz/robotName/commands/shooter/ShootFromInFunnel.java
  src/main/java/edu/greenblitz/robotName/subsystems/shooter/Pivot/PivotConstants.java
  src/main/java/edu/greenblitz/robotName/subsystems/swerve/Chassis/ChassisConstants.java
Labels: Feature Improvement, High-Priority

#118 yoav - fix flywheel
  src/main/java/edu/greenblitz/robotName/RobotConstants.java
  src/main/java/edu/greenblitz/robotName/commands/shooter/flyWheel/RunFlyWheelByVelocity.java
  src/main/java/edu/greenblitz/robotName/subsystems/shooter/FlyWheel/FalconFlyWheel/FalconFlyWheel.java
  src/main/java/edu/greenblitz/robotName/subsystems/shooter/FlyWheel/FalconFlyWheel/FalconFlyWheelConstants.java
  src/main/java/edu/greenblitz/robotName/subsystems/shooter/FlyWheel/FlyWheelFactory.java
  src/main/java/edu/greenblitz/robotName/subsystems/shooter/FlyWheel/FlyWheelInputs.java
  src/main/java/edu/greenblitz/robotName/subsystems/shooter/FlyWheel/NeoFlyWheel/NeoFlyWheel.java
  src/main/java/edu/greenblitz/robotName/subsystems/shooter/FlyWheel/simulationFlyWheel/SimulationFlyWheel.java
Labels: Bug-Fix, High-Priority

#117 Shooting Improvement
  src/main/java/edu/greenblitz/robotName/Robot.java
  src/main/java/edu/greenblitz/robotName/commands/swerve/MoveToPosition.java
  src/main/java/edu/greenblitz/robotName/shootingStateService/ShootingPositionConstants.java
  src/main/java/edu/greenblitz/robotName/shootingStateService/ShootingStateCalculations.java
  src/main/java/edu/greenblitz/robotName/subsystems/swerve/Chassis/ChassisConstants.java
  src/main/java/edu/greenblitz/robotName/utils/GBCircle.java
  src/main/java/edu/greenblitz/robotName/utils/GBMath.java
  src/main/java/edu/greenblitz/robotName/utils/GBPathFinding/GBAutoBuilder.java
  src/main/java/edu/greenblitz/robotName/utils/GBPathFinding/GBPathFindHolonomic.java
  src/main/java/edu/greenblitz/robotName/utils/GBPathFinding/GBPathfindingCommand.java
  src/main/java/edu/greenblitz/robotName/utils/shootingCalculations/ShootingZone.java
Labels: Feature Improvement, High-Priority

#123 Shooting zones
  src/main/java/edu/greenblitz/robotName/OI.java
  src/main/java/edu/greenblitz/robotName/Robot.java
  src/main/java/edu/greenblitz/robotName/commands/shooter/ShootFromCloseRange.java
  src/main/java/edu/greenblitz/robotName/commands/shooter/shootingState/GoToShootingState.java
  src/main/java/edu/greenblitz/robotName/commands/shooter/shootingState/GoToShootingStateAndShoot.java
  src/main/java/edu/greenblitz/robotName/commands/shooter/shootingState/MoveShooterToShootingAngle.java
  src/main/java/edu/greenblitz/robotName/commands/swerve/MoveRobotToShootingPosition.java
  src/main/java/edu/greenblitz/robotName/commands/swerve/MoveToPosition.java
  src/main/java/edu/greenblitz/robotName/shootingStateService/ShootingPositionConstants.java
  src/main/java/edu/greenblitz/robotName/shootingStateService/ShootingStateCalculations.java
  src/main/java/edu/greenblitz/robotName/subsystems/shooter/pivot/Pivot.java
  src/main/java/edu/greenblitz/robotName/subsystems/swerve/chassis/ChassisConstants.java
  src/main/java/edu/greenblitz/robotName/utils/AutonomousSelector.java
  src/main/java/edu/greenblitz/robotName/utils/GBCircle.java
  src/main/java/edu/greenblitz/robotName/utils/GBPathFinding/GBAutoBuilder.java
  src/main/java/edu/greenblitz/robotName/utils/GBPathFinding/GBCommandUtil.java
  src/main/java/edu/greenblitz/robotName/utils/GBPathFinding/GBPPLibTelemetry.java
  src/main/java/edu/greenblitz/robotName/utils/GBPathFinding/GBPathFindHolonomic.java
  src/main/java/edu/greenblitz/robotName/utils/GBPathFinding/GBPathPlannerAuto.java
  src/main/java/edu/greenblitz/robotName/utils/GBPathFinding/GBPathfindingCommand.java
  src/main/java/edu/greenblitz/robotName/utils/shootingCalculations/ShootingZone.java
Labels: Feature Improvement

#121 Ran - switched button A to score to amp
  src/main/java/edu/greenblitz/robotName/OI.java
Labels: Minor Change

#126 Robot name changing and some presetpositions
  src/main/java/edu/greenblitz/robotName/Field.java
  src/main/java/edu/greenblitz/robotName/OI.java
  src/main/java/edu/greenblitz/robotName/Robot.java
  src/main/java/edu/greenblitz/robotName/RobotConstants.java
  src/main/java/edu/greenblitz/robotName/commands/arm/MoveElbowAndWrist.java
  src/main/java/edu/greenblitz/robotName/commands/arm/MoveElbowAndWristToSafe.java
  src/main/java/edu/greenblitz/robotName/commands/arm/elbow/MoveElbowToAngle.java
  src/main/java/edu/greenblitz/robotName/commands/arm/wrist/MoveWristToAngle.java
  src/main/java/edu/greenblitz/robotName/subsystems/arm/elbow/ElbowFactory.java
  src/main/java/edu/greenblitz/robotName/subsystems/arm/roller/RollerFactory.java
  src/main/java/edu/greenblitz/robotName/subsystems/arm/wrist/WristFactory.java
  src/main/java/edu/greenblitz/robotName/subsystems/gyros/GyroFactory.java
  src/main/java/edu/greenblitz/robotName/subsystems/intake/IntakeFactory.java
  src/main/java/edu/greenblitz/robotName/subsystems/lifter/LifterFactory.java
  src/main/java/edu/greenblitz/robotName/subsystems/shooter/FlyWheel/FlyWheelFactory.java
  src/main/java/edu/greenblitz/robotName/subsystems/shooter/funnel/FunnelFactory.java
  src/main/java/edu/greenblitz/robotName/subsystems/shooter/pivot/PivotFactory.java
  src/main/java/edu/greenblitz/robotName/subsystems/swerve/chassis/SwerveChassis.java
  src/main/java/edu/greenblitz/robotName/subsystems/swerve/modules/SwerveModuleFactory.java
Labels: Minor Change

#128 April tags
  src/main/java/edu/greenblitz/robotName/Field.java
Labels: Feature Improvement

#127 Lifter Solenoid final
  src/main/java/edu/greenblitz/robotName/commands/lifter/ExtendLifter.java
  src/main/java/edu/greenblitz/robotName/commands/lifter/LiftUp.java
  src/main/java/edu/greenblitz/robotName/commands/lifter/RetractLifter.java
  src/main/java/edu/greenblitz/robotName/subsystems/lifter/ILifter.java
  src/main/java/edu/greenblitz/robotName/subsystems/lifter/Lifter.java
  src/main/java/edu/greenblitz/robotName/subsystems/lifter/LifterConstants.java
  src/main/java/edu/greenblitz/robotName/subsystems/lifter/LifterInputs.java
  src/main/java/edu/greenblitz/robotName/subsystems/lifter/neoLifter/NeoLifter.java
  src/main/java/edu/greenblitz/robotName/subsystems/lifter/neoLifter/NeoLifterConstants.java
  src/main/java/edu/greenblitz/robotName/subsystems/lifter/replayLifter/ReplayLifter.java
  src/main/java/edu/greenblitz/robotName/subsystems/lifter/simulationLifter/SimulationLifter.java
  src/main/java/edu/greenblitz/robotName/subsystems/lifter/simulationLifter/SimulationLifterConstants.java
Labels: New Feature, High-Priority

#129 Yoav - Fix talons code
  src/main/java/edu/greenblitz/robotName/subsystems/arm/elbow/ElbowFactory.java
  src/main/java/edu/greenblitz/robotName/subsystems/arm/elbow/ElbowInputs.java
  src/main/java/edu/greenblitz/robotName/subsystems/arm/elbow/falconElbow/FalconElbow.java
  src/main/java/edu/greenblitz/robotName/subsystems/arm/elbow/falconElbow/FalconElbowConstants.java
  src/main/java/edu/greenblitz/robotName/subsystems/arm/elbow/neoElbow/NeoElbow.java
  src/main/java/edu/greenblitz/robotName/subsystems/arm/elbow/simulationElbow/SimulationElbow.java
  src/main/java/edu/greenblitz/robotName/subsystems/shooter/FlyWheel/falconFlyWheel/FalconFlyWheel.java
  src/main/java/edu/greenblitz/robotName/subsystems/shooter/FlyWheel/falconFlyWheel/FalconFlyWheelConstants.java
  src/main/java/edu/greenblitz/robotName/subsystems/shooter/mechanism/ShooterMechanism.java
  src/main/java/edu/greenblitz/robotName/subsystems/shooter/mechanism/ShooterMechanismConstants.java
  src/main/java/edu/greenblitz/robotName/subsystems/shooter/pivot/falconPivot/FalconPivot.java
  src/main/java/edu/greenblitz/robotName/subsystems/shooter/pivot/falconPivot/FalconPivotConstants.java
  src/main/java/edu/greenblitz/robotName/utils/sysId/falconSysId/SysIdFalcon.java
  src/main/java/edu/greenblitz/robotName/utils/sysId/falconSysId/SysIdFalconConstants.java
Labels: Bug-Fix, Feature Improvement, Minor Change

#130 Ran - Scoring to Amp or Shooter Automatically and clean code
  src/main/java/edu/greenblitz/robotName/commands/ScoreToScoringMode.java
  src/main/java/edu/greenblitz/robotName/commands/shooter/shootingState/GoToAndShootToSpeaker.java
Labels: Feature Improvement

#125 Note simulation
  src/main/java/edu/greenblitz/robotName/OI.java
  src/main/java/edu/greenblitz/robotName/Robot.java
  src/main/java/edu/greenblitz/robotName/RobotConstants.java
  src/main/java/edu/greenblitz/robotName/commands/shooter/flyWheel/RunFlyWheelBySpeakerInterpolationVelocity.java
  src/main/java/edu/greenblitz/robotName/commands/shooter/flyWheel/RunFlyWheelByVelocity.java
  src/main/java/edu/greenblitz/robotName/commands/shooter/flyWheel/ShootSimulationNote.java
  src/main/java/edu/greenblitz/robotName/commands/shooter/flyWheel/StopFlyWheel.java
  src/main/java/edu/greenblitz/robotName/commands/swerve/MoveToClimbPosition.java
  src/main/java/edu/greenblitz/robotName/shootingStateService/ShootingStateCalculations.java
  src/main/java/edu/greenblitz/robotName/subsystems/Dashboard.java
  src/main/java/edu/greenblitz/robotName/subsystems/shooter/FlyWheel/FlyWheelConstants.java
  src/main/java/edu/greenblitz/robotName/subsystems/swerve/chassis/SwerveChassis.java
Labels: New Feature, Low-Priority

#135 yoav - calibrate left flywheel ff
  src/main/java/edu/greenblitz/robotName/subsystems/shooter/FlyWheel/falconFlyWheel/FalconFlyWheelConstants.java
Labels: Feature Improvement, High-Priority

#136 yoav - Flywheel calibration
  src/main/java/edu/greenblitz/robotName/OI.java
  src/main/java/edu/greenblitz/robotName/subsystems/shooter/FlyWheel/falconFlyWheel/FalconFlyWheelConstants.java
  src/main/java/edu/greenblitz/robotName/utils/sysId/falconSysId/SysIdFalcon.java
  src/main/java/edu/greenblitz/robotName/utils/sysId/falconSysId/SysIdFalconConstants.java
Labels: Bug-Fix, Feature Improvement, High-Priority

#132 Latency and more fixes
  src/main/java/edu/greenblitz/robotName/Robot.java
  src/main/java/edu/greenblitz/robotName/RobotConstants.java
  src/main/java/edu/greenblitz/robotName/commands/shooter/pivot/MovePivotByJoystick.java
  src/main/java/edu/greenblitz/robotName/commands/swerve/RotateToAngle.java
  src/main/java/edu/greenblitz/robotName/subsystems/arm/elbow/falconElbow/FalconElbow.java
  src/main/java/edu/greenblitz/robotName/subsystems/arm/elbow/falconElbow/FalconElbowConstants.java
  src/main/java/edu/greenblitz/robotName/subsystems/gyros/SimulationGyro.java
  src/main/java/edu/greenblitz/robotName/subsystems/shooter/FlyWheel/falconFlyWheel/FalconFlyWheel.java
  src/main/java/edu/greenblitz/robotName/subsystems/shooter/FlyWheel/falconFlyWheel/FalconFlyWheelConstants.java
  src/main/java/edu/greenblitz/robotName/subsystems/shooter/pivot/falconPivot/FalconPivot.java
  src/main/java/edu/greenblitz/robotName/subsystems/shooter/pivot/falconPivot/FalconPivotConstants.java
  src/main/java/edu/greenblitz/robotName/subsystems/swerve/SwerveModuleConfigObject.java
  src/main/java/edu/greenblitz/robotName/subsystems/swerve/chassis/ChassisConstants.java
  src/main/java/edu/greenblitz/robotName/subsystems/swerve/chassis/ISwerveChassis.java
  src/main/java/edu/greenblitz/robotName/subsystems/swerve/modules/ISwerveModule.java
  src/main/java/edu/greenblitz/robotName/subsystems/swerve/modules/SwerveModule.java
  src/main/java/edu/greenblitz/robotName/subsystems/swerve/modules/SwerveModuleInputs.java
  src/main/java/edu/greenblitz/robotName/subsystems/swerve/modules/kazaSwerveModule/KazaSwerveConstants.java
  src/main/java/edu/greenblitz/robotName/subsystems/swerve/modules/mk4iSwerveModule/MK4ISwerveModule.java
  src/main/java/edu/greenblitz/robotName/subsystems/swerve/modules/mk4iSwerveModule/MK4iSwerveConstants.java
  src/main/java/edu/greenblitz/robotName/subsystems/swerve/modules/simulationSwerveModule/SimulationConstants.java
  src/main/java/edu/greenblitz/robotName/subsystems/swerve/modules/simulationSwerveModule/SimulationSwerveModule.java
  src/main/java/edu/greenblitz/robotName/utils/motors/GBTalonFXPro.java
Labels: New Feature, Feature Improvement, High-Priority

#146 yoav - One bb intake
  src/main/java/edu/greenblitz/robotName/commands/intake/NoteToIntake.java
  src/main/java/edu/greenblitz/robotName/subsystems/intake/Intake.java
  src/main/java/edu/greenblitz/robotName/subsystems/intake/IntakeInputs.java
  src/main/java/edu/greenblitz/robotName/subsystems/intake/neoIntake/NeoIntake.java
  src/main/java/edu/greenblitz/robotName/subsystems/intake/neoIntake/NeoIntakeConstants.java
  src/main/java/edu/greenblitz/robotName/subsystems/intake/simulationIntake/SimulationIntake.java
  src/main/java/edu/greenblitz/robotName/utils/motors/GBTalonFXPro.java
Labels: Bug-Fix, Feature Improvement, Minor Change

#138 Calibration
  src/main/java/edu/greenblitz/robotName/OI.java
  src/main/java/edu/greenblitz/robotName/Robot.java
  src/main/java/edu/greenblitz/robotName/commands/NoteToShooter.java
  src/main/java/edu/greenblitz/robotName/commands/shooter/flyWheel/RunFlyWheelByVelocity.java
  src/main/java/edu/greenblitz/robotName/commands/shooter/pivot/PivotDefaultCommand.java
  src/main/java/edu/greenblitz/robotName/subsystems/Dashboard.java
  src/main/java/edu/greenblitz/robotName/subsystems/gyros/Pigeon2Gyro.java
  src/main/java/edu/greenblitz/robotName/subsystems/intake/IntakeConstants.java
  src/main/java/edu/greenblitz/robotName/subsystems/intake/neoIntake/NeoIntake.java
  src/main/java/edu/greenblitz/robotName/subsystems/intake/neoIntake/NeoIntakeConstants.java
  src/main/java/edu/greenblitz/robotName/subsystems/shooter/FlyWheel/falconFlyWheel/FalconFlyWheel.java
  src/main/java/edu/greenblitz/robotName/subsystems/shooter/FlyWheel/falconFlyWheel/FalconFlyWheelConstants.java
  src/main/java/edu/greenblitz/robotName/subsystems/shooter/funnel/FunnelConstants.java
  src/main/java/edu/greenblitz/robotName/subsystems/shooter/funnel/FunnelFactory.java
  src/main/java/edu/greenblitz/robotName/subsystems/shooter/funnel/neoFunnel/NeoFunnel.java
  src/main/java/edu/greenblitz/robotName/subsystems/shooter/funnel/neoFunnel/NeoFunnelConstants.java
  src/main/java/edu/greenblitz/robotName/subsystems/shooter/pivot/Pivot.java
  src/main/java/edu/greenblitz/robotName/subsystems/shooter/pivot/PivotConstants.java
  src/main/java/edu/greenblitz/robotName/subsystems/shooter/pivot/PivotInputs.java
  src/main/java/edu/greenblitz/robotName/subsystems/shooter/pivot/falconPivot/FalconPivot.java
  src/main/java/edu/greenblitz/robotName/subsystems/shooter/pivot/falconPivot/FalconPivotConstants.java
  src/main/java/edu/greenblitz/robotName/subsystems/shooter/pivot/simulationPivot/SimulationPivot.java
  src/main/java/edu/greenblitz/robotName/subsystems/swerve/SwerveModuleConfigObject.java
  src/main/java/edu/greenblitz/robotName/subsystems/swerve/chassis/SwerveChassis.java
  src/main/java/edu/greenblitz/robotName/subsystems/swerve/modules/kazaSwerveModule/KazaSwerveModule.java
  src/main/java/edu/greenblitz/robotName/subsystems/swerve/modules/mk4iSwerveModule/MK4ISwerveModule.java
  src/main/java/edu/greenblitz/robotName/subsystems/swerve/modules/mk4iSwerveModule/MK4iSwerveConstants.java
  src/main/java/edu/greenblitz/robotName/utils/SysId/falconSysId/SysIdFalcon.java
  src/main/java/edu/greenblitz/robotName/utils/SysId/falconSysId/SysIdFalconConstants.java
  src/main/java/edu/greenblitz/robotName/utils/SysId/neoSysId/SysIdNeo.java
  src/main/java/edu/greenblitz/robotName/utils/SysId/neoSysId/SysIdNeoConstants.java
  src/main/java/edu/greenblitz/robotName/utils/sysId/falconSysId/SysIdFalconConstants.java
Labels: Feature Improvement, High-Priority

#139 yoav - bag wrist
  src/main/java/edu/greenblitz/robotName/subsystems/arm/wrist/IWrist.java
  src/main/java/edu/greenblitz/robotName/subsystems/arm/wrist/ReplayWrist.java
  src/main/java/edu/greenblitz/robotName/subsystems/arm/wrist/Wrist.java
  src/main/java/edu/greenblitz/robotName/subsystems/arm/wrist/WristFactory.java
  src/main/java/edu/greenblitz/robotName/subsystems/arm/wrist/WristInputs.java
  src/main/java/edu/greenblitz/robotName/subsystems/arm/wrist/neoWrist/NeoWrist.java
  src/main/java/edu/greenblitz/robotName/subsystems/arm/wrist/simulationWrist/SimulationWrist.java
  src/main/java/edu/greenblitz/robotName/subsystems/arm/wrist/srxWrist/SRXWrist.java
  src/main/java/edu/greenblitz/robotName/subsystems/arm/wrist/srxWrist/SRXWristConstants.java
  src/main/java/edu/greenblitz/robotName/utils/Conversions.java
  src/main/java/edu/greenblitz/robotName/utils/GBCircle.java
Labels: New Feature, High-Priority

#143 Eject Note
  src/main/java/edu/greenblitz/robotName/commands/arm/roller/ReleaseNoteFromRoller.java
  src/main/java/edu/greenblitz/robotName/commands/getNoteToSystem/EjectNote.java
  src/main/java/edu/greenblitz/robotName/commands/intake/ReverseRunIntake.java
Labels: New Feature

#142 Resetting each subsystem button
  src/main/java/edu/greenblitz/robotName/commands/ResetSubsystems.java
  src/main/java/edu/greenblitz/robotName/subsystems/swerve/chassis/SwerveChassis.java
Labels: New Feature

#147 yoav - fixing gyro
  src/main/java/edu/greenblitz/robotName/commands/getNoteToSystem/EjectNote.java
  src/main/java/edu/greenblitz/robotName/commands/intake/ReverseRunIntake.java
  src/main/java/edu/greenblitz/robotName/subsystems/gyros/Pigeon2Gyro.java
  src/main/java/edu/greenblitz/robotName/utils/GBCircle.java
Labels: Bug-Fix

#144 New auto
  src/main/deploy/pathplanner/autos/just 2.auto
  src/main/deploy/pathplanner/paths/2 to speaker.path
  src/main/deploy/pathplanner/paths/speaker start to 2.path
  src/main/java/edu/greenblitz/robotName/Robot.java
Labels: New Feature, Feature Improvement

#149 Better pregional
  src/main/java/edu/greenblitz/robotName/OI.java
  src/main/java/edu/greenblitz/robotName/Robot.java
  src/main/java/edu/greenblitz/robotName/VisionConstants.java
  src/main/java/edu/greenblitz/robotName/commands/CollectNote.java
  src/main/java/edu/greenblitz/robotName/commands/intake/NoteFromIntakeToShooter.java
  src/main/java/edu/greenblitz/robotName/commands/intake/NoteToShooter.java
  src/main/java/edu/greenblitz/robotName/commands/shooter/ShootToSpeakerFromClose.java
  src/main/java/edu/greenblitz/robotName/subsystems/arm/elbow/falconElbow/FalconElbowConstants.java
  src/main/java/edu/greenblitz/robotName/subsystems/intake/IntakeConstants.java
  src/main/java/edu/greenblitz/robotName/subsystems/lifter/neoLifter/NeoLifter.java
  src/main/java/edu/greenblitz/robotName/subsystems/lifter/neoLifter/NeoLifterConstants.java
  src/main/java/edu/greenblitz/robotName/subsystems/shooter/FlyWheel/FlyWheelConstants.java
  src/main/java/edu/greenblitz/robotName/subsystems/shooter/funnel/FunnelConstants.java
  src/main/java/edu/greenblitz/robotName/subsystems/shooter/pivot/PivotConstants.java
  src/main/java/edu/greenblitz/robotName/subsystems/shooter/pivot/falconPivot/FalconPivot.java
  src/main/java/edu/greenblitz/robotName/subsystems/shooter/pivot/falconPivot/FalconPivotConstants.java
  src/main/java/edu/greenblitz/robotName/subsystems/swerve/chassis/ChassisConstants.java
  src/main/java/edu/greenblitz/robotName/subsystems/swerve/chassis/SwerveChassis.java
  src/main/java/edu/greenblitz/robotName/subsystems/swerve/modules/mk4iSwerveModule/MK4iSwerveConstants.java
Labels: Bug-Fix, Feature Improvement, In Testing, High-Priority

#154 yoav - very very small change
  src/main/java/edu/greenblitz/robotName/commands/CollectNote.java
Labels: Bug-Fix, Minor Change

#152 calibrated chassis
  src/main/java/edu/greenblitz/robotName/subsystems/swerve/modules/mk4iSwerveModule/MK4ISwerveModule.java
  src/main/java/edu/greenblitz/robotName/subsystems/swerve/modules/mk4iSwerveModule/MK4iSwerveConstants.java
  src/main/java/edu/greenblitz/robotName/utils/SysId/falconSysId/SysIdFalcon.java
  src/main/java/edu/greenblitz/robotName/utils/SysId/falconSysId/SysIdFalconConstants.java
  src/main/java/edu/greenblitz/robotName/utils/SysId/falconSysId/SysIdFalconSwerve.java
  src/main/java/edu/greenblitz/robotName/utils/SysId/falconSysId/SysIdFalconSwerveConstants.java
  src/main/java/edu/greenblitz/robotName/utils/hid/SmartJoystick.java
Labels: Bug-Fix, Feature Improvement, High-Priority
