Repository GreenBlitz/CRRRRESCENDO, pull requests merged in 2024-03, with the labels that each got.

#165 fix master for the trillionth time
  src/main/java/edu/greenblitz/robotName/OI.java
Labels: Bug-Fix, High-Priority, Minor Change

#141 LED
  src/main/java/edu/greenblitz/robotName/OI.java
  src/main/java/edu/greenblitz/robotName/Robot.java
  src/main/java/edu/greenblitz/robotName/RobotConstants.java
  src/main/java/edu/greenblitz/robotName/ScoringModeSelector.java
  src/main/java/edu/greenblitz/robotName/commands/LED/UpdateLEDStateDefaultCommand.java
  src/main/java/edu/greenblitz/robotName/subsystems/LED/LED.java
  src/main/java/edu/greenblitz/robotName/subsystems/LED/LEDConstants.java
  src/main/java/edu/greenblitz/robotName/subsystems/LED/Section.java
  src/main/java/edu/greenblitz/robotName/subsystems/arm/roller/Roller.java
  src/main/java/edu/greenblitz/robotName/subsystems/arm/wrist/neoWrist/NeoWristConstants.java
  src/main/java/edu/greenblitz/robotName/subsystems/intake/IntakeConstants.java
  vendordeps/PathplannerLib.json
Labels: New Feature

#171 yoav - Arm
  src/main/deploy/pathplanner/autos/checkck.auto
  src/main/deploy/pathplanner/paths/check.path
  src/main/java/edu/greenblitz/robotName/OI.java
  src/main/java/edu/greenblitz/robotName/Robot.java
  src/main/java/edu/greenblitz/robotName/ScoringModeSelector.java
  src/main/java/edu/greenblitz/robotName/commands/arm/NoteToArm.java
  src/main/java/edu/greenblitz/robotName/commands/arm/ScoreToAmp.java
  src/main/java/edu/greenblitz/robotName/commands/arm/elbow/ElbowDefaultCommand.java
  src/main/java/edu/greenblitz/robotName/commands/arm/roller/CollectNoteToRoller.java
  src/main/java/edu/greenblitz/robotName/commands/arm/roller/ReleaseNoteFromRoller.java
  src/main/java/edu/greenblitz/robotName/commands/arm/roller/RollerDefaultCommand.java
  src/main/java/edu/greenblitz/robotName/commands/arm/roller/RunByPowerAndCountRotations.java
  src/main/java/edu/greenblitz/robotName/commands/arm/roller/RunRollerByRotations.java
  src/main/java/edu/greenblitz/robotName/commands/arm/roller/runByPower/RunRollerClockwiseUntilObjectIsOut.java
  src/main/java/edu/greenblitz/robotName/commands/arm/wrist/WristDefaultCommand.java
  src/main/java/edu/greenblitz/robotName/commands/getNoteToSystem/CollectNoteToScoringModeForJoystick.java
  src/main/java/edu/greenblitz/robotName/commands/getNoteToSystem/MoveNoteBetweenShooterAndArm.java
  src/main/java/edu/greenblitz/robotName/commands/getNoteToSystem/MoveToTransferNotePosition.java
  src/main/java/edu/greenblitz/robotName/commands/getNoteToSystem/SafeMoveNoteBetweenShooterAndArm.java
  src/main/java/edu/greenblitz/robotName/commands/getNoteToSystem/TransferNote.java
  src/main/java/edu/greenblitz/robotName/commands/intake/NoteFromIntakeToShooterWithArm.java
  src/main/java/edu/greenblitz/robotName/commands/intake/NoteToShooterForJoystick.java
  src/main/java/edu/greenblitz/robotName/commands/intake/NoteToShooterWithoutArm.java
  src/main/java/edu/greenblitz/robotName/commands/intake/ReverseRunIntake.java
  src/main/java/edu/greenblitz/robotName/commands/shooter/NoteToShooterFromArm.java
  src/main/java/edu/greenblitz/robotName/subsystems/arm/elbow/Elbow.java
  src/main/java/edu/greenblitz/robotName/subsystems/arm/elbow/ElbowConstants.java
  src/main/java/edu/greenblitz/robotName/subsystems/arm/elbow/ElbowInputs.java
  src/main/java/edu/greenblitz/robotName/subsystems/arm/elbow/falconElbow/FalconElbow.java
  src/main/java/edu/greenblitz/robotName/subsystems/arm/elbow/neoElbow/NeoElbow.java
  src/main/java/edu/greenblitz/robotName/subsystems/arm/elbow/neoElbow/NeoElbowConstants.java
  src/main/java/edu/greenblitz/robotName/subsystems/arm/elbow/simulationElbow/SimulationElbow.java
  src/main/java/edu/greenblitz/robotName/subsystems/arm/roller/Roller.java
  src/main/java/edu/greenblitz/robotName/subsystems/arm/roller/RollerConstants.java
  src/main/java/edu/greenblitz/robotName/subsystems/arm/roller/neoRoller/NeoRoller.java
  src/main/java/edu/greenblitz/robotName/subsystems/arm/roller/neoRoller/NeoRollerConstants.java
  src/main/java/edu/greenblitz/robotName/subsystems/arm/wrist/Wrist.java
  src/main/java/edu/greenblitz/robotName/subsystems/arm/wrist/WristConstants.java
  src/main/java/edu/greenblitz/robotName/subsystems/arm/wrist/srxWrist/SRXWrist.java
  src/main/java/edu/greenblitz/robotName/subsystems/arm/wrist/srxWrist/SRXWristConstants.java
  src/main/java/edu/greenblitz/robotName/subsystems/shooter/funnel/neoFunnel/NeoFunnelConstants.java
Labels: New Feature, Feature Improvement, High-Priority

#173 vision and rotate to angle works!!!
  src/main/java/edu/greenblitz/robotName/OI.java
  src/main/java/edu/greenblitz/robotName/VisionConstants.java
  src/main/java/edu/greenblitz/robotName/commands/NoteToShooterForAuto.java
  src/main/java/edu/greenblitz/robotName/commands/arm/elbow/SafeMoveElbowToAngle.java
  src/main/java/edu/greenblitz/robotName/commands/shooter/flyWheel/FlyWheelDefaultCommand.java
  src/main/java/edu/greenblitz/robotName/commands/swerve/MoveByJoysticks.java
  src/main/java/edu/greenblitz/robotName/commands/swerve/RotateToPoint.java
  src/main/java/edu/greenblitz/robotName/commands/swerve/RotateToSpeaker.java
  src/main/java/edu/greenblitz/robotName/shootingStateService/ShootingPositionConstants.java
  src/main/java/edu/greenblitz/robotName/subsystems/Dashboard.java
  src/main/java/edu/greenblitz/robotName/subsystems/limelight/Limelight.java
  src/main/java/edu/greenblitz/robotName/subsystems/limelight/MultiLimelight.java
  src/main/java/edu/greenblitz/robotName/subsystems/shooter/FlyWheel/FlyWheelConstants.java
  src/main/java/edu/greenblitz/robotName/subsystems/shooter/pivot/Pivot.java
  src/main/java/edu/greenblitz/robotName/subsystems/swerve/chassis/ChassisConstants.java
  src/main/java/edu/greenblitz/robotName/subsystems/swerve/chassis/GetRotationSupplier.java
  src/main/java/edu/greenblitz/robotName/subsystems/swerve/chassis/SwerveChassis.java
  src/main/java/edu/greenblitz/robotName/subsystems/swerve/modules/mk4iSwerveModule/MK4ISwerveModule.java
Labels: New Feature, High-Priority

#180 yoav - fixed rumble
  src/main/java/edu/greenblitz/robotName/subsystems/LED/LED.java
Labels: High-Priority, Minor Change

#181 Dis 4
  .pathplanner/settings.json
  src/main/java/edu/greenblitz/robotName/OI.java
  src/main/java/edu/greenblitz/robotName/Robot.java
  src/main/java/edu/greenblitz/robotName/RobotConstants.java
  src/main/java/edu/greenblitz/robotName/commands/RumbleRomy.java
  src/main/java/edu/greenblitz/robotName/commands/arm/MoveElbowAndWristWithRunFunnel.java
  src/main/java/edu/greenblitz/robotName/commands/arm/elbow/ElbowDefaultCommand.java
  src/main/java/edu/greenblitz/robotName/commands/arm/roller/MoveNoteInRoller.java
  src/main/java/edu/greenblitz/robotName/commands/arm/roller/ReleaseNoteFromRollerToAmp.java
  src/main/java/edu/greenblitz/robotName/commands/arm/roller/RollerDefaultCommand.java
  src/main/java/edu/greenblitz/robotName/commands/arm/roller/RunRollerByJoystick.java
  src/main/java/edu/greenblitz/robotName/commands/arm/roller/RunRollerByRotations.java
  src/main/java/edu/greenblitz/robotName/commands/arm/roller/runByPower/RunRollerCounterClockwiseUntilNoteIsInside.java
  src/main/java/edu/greenblitz/robotName/commands/getNoteToSystem/CollectNoteToScoringMode.java
  src/main/java/edu/greenblitz/robotName/commands/getNoteToSystem/TransferNote.java
  src/main/java/edu/greenblitz/robotName/commands/intake/CollectNoteFromGround.java
  src/main/java/edu/greenblitz/robotName/commands/intake/CollectNoteFromGroundWithPivotForJoystick.java
  src/main/java/edu/greenblitz/robotName/commands/intake/NoteFromIntakeToShooterWithArm.java
  src/main/java/edu/greenblitz/robotName/commands/shooter/pivot/MovePivotToAngle.java
  src/main/java/edu/greenblitz/robotName/commands/shooter/pivot/PivotCommand.java
  src/main/java/edu/greenblitz/robotName/commands/shooter/pivot/PivotDefaultCommand.java
  src/main/java/edu/greenblitz/robotName/commands/swerve/MoveByJoysticks.java
  src/main/java/edu/greenblitz/robotName/subsystems/arm/elbow/Elbow.java
  src/main/java/edu/greenblitz/robotName/subsystems/arm/elbow/ElbowConstants.java
  src/main/java/edu/greenblitz/robotName/subsystems/arm/elbow/falconElbow/FalconElbow.java
  src/main/java/edu/greenblitz/robotName/subsystems/arm/roller/Roller.java
  src/main/java/edu/greenblitz/robotName/subsystems/arm/roller/RollerConstants.java
  src/main/java/edu/greenblitz/robotName/subsystems/arm/roller/RollerInputs.java
  src/main/java/edu/greenblitz/robotName/subsystems/arm/roller/neoRoller/NeoRoller.java
  src/main/java/edu/greenblitz/robotName/subsystems/arm/roller/neoRoller/NeoRollerConstants.java
  src/main/java/edu/greenblitz/robotName/subsystems/arm/roller/simulationRoller/SimulationRoller.java
  src/main/java/edu/greenblitz/robotName/subsystems/arm/wrist/WristConstants.java
  src/main/java/edu/greenblitz/robotName/subsystems/lifter/Lifter.java
  src/main/java/edu/greenblitz/robotName/subsystems/lifter/LifterFactory.java
  src/main/java/edu/greenblitz/robotName/subsystems/lifter/LifterInputs.java
  src/main/java/edu/greenblitz/robotName/subsystems/lifter/neoLifter/NeoLifter.java
  src/main/java/edu/greenblitz/robotName/subsystems/shooter/FlyWheel/falconFlyWheel/FalconFlyWheel.java
  src/main/java/edu/greenblitz/robotName/subsystems/shooter/funnel/FunnelFactory.java
  src/main/java/edu/greenblitz/robotName/subsystems/shooter/pivot/PivotConstants.java
  src/main/java/edu/greenblitz/robotName/subsystems/shooter/pivot/falconPivot/FalconPivot.java
  src/main/java/edu/greenblitz/robotName/subsystems/swerve/chassis/ChassisConstants.java
  src/main/java/edu/greenblitz/robotName/subsystems/swerve/chassis/SwerveChassis.java
  src/main/java/edu/greenblitz/robotName/subsystems/swerve/modules/mk4iSwerveModule/MK4ISwerveModule.java
  src/main/java/edu/greenblitz/robotName/utils/AutonomousSelector.java
  src/main/java/edu/greenblitz/robotName/utils/hid/AxisButton.java
  src/main/java/edu/greenblitz/robotName/utils/hid/SmartJoystick.java
Labels: Bug-Fix, New Feature, Feature Improvement, High-Priority

#184 yoav - Falcon Lifter
  src/main/java/edu/greenblitz/robotName/subsystems/lifter/Lifter.java
  src/main/java/edu/greenblitz/robotName/subsystems/lifter/LifterConstants.java
  src/main/java/edu/greenblitz/robotName/subsystems/lifter/LifterFactory.java
  src/main/java/edu/greenblitz/robotName/subsystems/lifter/LifterInputs.java
  src/main/java/edu/greenblitz/robotName/subsystems/lifter/falconLifter/FalconLifter.java
  src/main/java/edu/greenblitz/robotName/subsystems/lifter/falconLifter/FalconLifterConstants.java
  src/main/java/edu/greenblitz/robotName/subsystems/lifter/neoLifter/NeoLifter.java
  src/main/java/edu/greenblitz/robotName/subsystems/lifter/neoLifter/NeoLifterConstants.java
  src/main/java/edu/greenblitz/robotName/subsystems/lifter/simulationLifter/SimulationLifter.java
Labels: New Feature

#182 yoav - climb mode
  src/main/java/edu/greenblitz/robotName/ScoringMode.java
  src/main/java/edu/greenblitz/robotName/ScoringModeSelector.java
  src/main/java/edu/greenblitz/robotName/commands/switchMode/FullySwitchScoringMode.java
  src/main/java/edu/greenblitz/robotName/commands/switchMode/SetScoringMode.java
  src/main/java/edu/greenblitz/robotName/commands/switchMode/SwitchingScoringModeMovement.java
  src/main/java/edu/greenblitz/robotName/subsystems/Dashboard.java
  src/main/java/edu/greenblitz/robotName/utils/ScoringMode.java
Labels: Minor Change

#186 yoav - fixes to simulation
  src/main/java/edu/greenblitz/robotName/OI.java
  src/main/java/edu/greenblitz/robotName/commands/getNoteToSystem/CollectNoteToScoringModeForJoystick.java
  src/main/java/edu/greenblitz/robotName/commands/getNoteToSystem/CollectNoteToScoringModeWithPivotForJoystick.java
  src/main/java/edu/greenblitz/robotName/commands/intake/CollectNoteFromGroundWithPivotForJoystick.java
  src/main/java/edu/greenblitz/robotName/subsystems/lifter/simulationLifter/SimulationLifter.java
  src/main/java/edu/greenblitz/robotName/subsystems/swerve/chassis/SwerveChassis.java
Labels: Bug-Fix, High-Priority

#189 yoav - Fix Transfer
  src/main/java/edu/greenblitz/robotName/subsystems/arm/roller/RollerConstants.java
Labels: Bug-Fix, Minor Change

#188 LED FIX
  src/main/java/edu/greenblitz/robotName/subsystems/LED/LED.java
Labels: Bug-Fix, Minor Change

#190 yoav - fixes
  src/main/java/edu/greenblitz/robotName/Robot.java
  src/main/java/edu/greenblitz/robotName/utils/hid/AxisButton.java
  src/main/java/edu/greenblitz/robotName/utils/hid/SmartJoystick.java
Labels: Bug-Fix, Minor Change

#193 yoav - added align note in funnel after note in shooter
  src/main/java/edu/greenblitz/robotName/commands/getNoteToSystem/CollectNoteToScoringModeForJoystick.java
  src/main/java/edu/greenblitz/robotName/commands/intake/CollectNoteFromGround.java
  src/main/java/edu/greenblitz/robotName/commands/shooter/funnel/AlignNoteInFunnel.java
Labels: New Feature, Feature Improvement, In Testing, High-Priority
